version: '3.1'

services:
  mongo-rs0-1:
    image: mongo-start
    build: tools/mongodb-replicaset/mongo-rs0-1
    ports:
      - 27017:27017
    volumes:
      - mongo-rs0-1:/data/db
    depends_on:
      - mongo-rs0-2
      - mongo-rs0-3

  mongo-rs0-2:
    image: mongo:3.4
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - 27018:27017
    volumes:
      - mongo-rs0-2:/data/db

  mongo-rs0-3:
    image: mongo:3.4
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - 27019:27017
    volumes:
      - mongo-rs0-3:/data/db

  setup-rs:
    image: setup-rs
    build: tools/mongodb-replicaset/setup
    depends_on:
      - mongo-rs0-1
volumes:
  mongo-rs0-1:
  mongo-rs0-2:
  mongo-rs0-3:
