version: '3.1'
services:
  api:
    container_name: api
    build:
      context: .
      args:
        NODE_ENV: development
    hostname: api
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=5000
      - LISTEN_IP=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/app
    ports:
      - '3000:3000'
      - '127.0.0.1:9229:9229' # V8 inspector for debugging
    volumes:
      - yarn:/home/node/.cache/yarn
      - .:/opt/app:delegated
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 src/server.js
volumes:
  yarn:
  notused:
  mongo:
