port: 10004

logger:
  level: debug
  transports:
    console:
      outputFormat: rich

mongodb:
  host: mongo-rs0-1
  port: 27017
  username: ''
  password: ''
  database: skylight
  replicas:
    - host: mongo-rs0-2
      port: 27017
    - host: mongo-rs0-3
      port: 27017
  options:
    useNewUrlParser: true
    replicaSet: 'rs0'
    readPreference: primaryPreferred

mongoose:
  useNewUrlParser: true

amqp:
  hostname: localhost
  port: 5672
  vhost: ''
  username: ''
  password: ''
  maxReconnectTries: 10
  exchanges:
    mqttTopic: amq.topic
  queues:
    assignments: assignments

externalServices:
  assignment:
    url: http://localhost:8080
  bulwark:
    url: http://localhost:10103

constants:
  auth:
    scopes:
      assignment:
        assign:
          any: assignment:assign
